<a href="https://colab.research.google.com/github/ulissigroup/math-methods-chemical-engineering/blob/master/lecture_notes/07b-numerical-eigenvalues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
$$\newcommand{\arr}[1]{\underline{\underline{#1}}}$$    
$$\newcommand{\vec}[1]{\underline{#1}}$$   
$$\require{mhchem}$$

# Eigenvectors in python

Unsurprisingly, there is a function to calculate eigenvalues and eigenvectors in python! 
* For most cases, we can use the ```np.linalg.eig``` function
* If we only wanted the eigenvalues, ```np.linalg.eigvals``` will just calculate those. 


## Example 1: real roots

Let's start with a simple example where we already know the roots: a lower triangular matrix
\begin{align}
\arr{A}=\begin{bmatrix}6&10&6 \\ 0&8&12 \\ 0&0&2 \end{bmatrix} 
\end{align}

In [1]:
import numpy as np

A = np.array([[6,10,6],
              [0,8,2],
              [0,0,2]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[6. 8. 2.]
[[ 1.          0.98058068 -0.53452248]
 [ 0.          0.19611614 -0.26726124]
 [ 0.          0.          0.80178373]]


In [2]:
import numpy as np

A = np.array([[6,10,6], 
              [0,8,12],
              [0,0,2]])

# calculate the eigenvalues of A:
eigenvalues = np.linalg.eigvals(A)
print('The eigenvalues of A are: %s'%eigenvalues)

#Calculate both the eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)
# calculate the eigenvalues of A:
print('The eigenvalues of A are: %s'%eigenvalues)

#Print the first eigenvalue and eigenvector
print('The eigenvalue corresponding to lambda=%d is: %s'%(eigenvalues[0],eigenvectors[:,0]))

# We can also iterate over each eigenvalue/eigenvector pair
for i in range(len(eigenvalues)):
  print('The eigenvalue corresponding to lambda=%d is: %s'%(eigenvalues[i],eigenvectors[:,i]))


The eigenvalues of A are: [6. 8. 2.]
The eigenvalues of A are: [6. 8. 2.]
The eigenvalue corresponding to lambda=6 is: [1. 0. 0.]
The eigenvalue corresponding to lambda=6 is: [1. 0. 0.]
The eigenvalue corresponding to lambda=8 is: [0.98058068 0.19611614 0.        ]
The eigenvalue corresponding to lambda=2 is: [ 0.84270097 -0.48154341  0.24077171]


Let's compare these to the known values from lecture 6:

Eigenspace corresponding to $\arr{A}$ :
\begin{array}{}
6, \begin{bmatrix} 1\\0\\0 \end{bmatrix} ; & 8,\begin{bmatrix} 5\\1\\0 \end{bmatrix}; & 2, \begin{bmatrix} 7\\-4\\2\end{bmatrix} ; & \vec{x}=\vec{0}
\end{array}

Notice that the eigenvectors returned by numpy are the same ratios, but different absolute numbers. We can rescale these if we need. 


In [3]:
eigenvectors[:,1]/eigenvectors[1,1]

array([5., 1., 0.])

In [4]:
  print('The eigenvalue corresponding to lambda=%d is: %s'%(eigenvalues[2],eigenvectors[:,2]/eigenvectors[2,2]*2))

The eigenvalue corresponding to lambda=2 is: [ 7. -4.  2.]


## Complex roots

$ \arr{A} = \begin{bmatrix} 1&2 \\ -2&1 \end{bmatrix} $

This is easy now that we know how to use ```np.linalg.eig```!

In [5]:
A = np.array([[1,2],
              [-2,1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[1.+2.j 1.-2.j]
[[0.        -0.70710678j 0.        +0.70710678j]
 [0.70710678+0.j         0.70710678-0.j        ]]


In [6]:
(1+2.j)**2

(-3+4j)

In [7]:
A = np.array([[1,2],[-2,1]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[1.+2.j 1.-2.j]
[[0.        -0.70710678j 0.        +0.70710678j]
 [0.70710678+0.j         0.70710678-0.j        ]]


Notice that numpy is using "j" to indicate a complex number. Otherwise things look pretty simple!

### Here are some examples of complex numbers:

In [8]:
a = 1+2.j
print('a=%s'%str(a))
print('a+1=%s'%str(a+1))
print('2a=%s'%str(2*a))

a=(1+2j)
a+1=(2+2j)
2a=(2+4j)


# In-class problem 

Calculate the eigenvalues and eigenvectors for the matrix 

$\arr{A} = \begin{bmatrix} 0&9&-12 \\ -9&0&20 \\ 12&-20&0 \end{bmatrix}$


# Population eigenvalue problem

Let's start with calculating the eigenvalues and eigenvectors of the population transition matrix $\arr{A}$

In [9]:
A = np.array([[0.3,0.2,0],
              [0.6,0.2,0],
              [0.1,0.6,1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[ 1.  -0.1  0.6]
[[ 0.          0.40824829 -0.32444284]
 [ 0.         -0.81649658 -0.48666426]
 [ 1.          0.40824829  0.81110711]]


Matches up with what we already know! 

Let's do a little example for a random starting population of 1000 people. 

In [10]:
# Generate three random numbers
p = np.random.rand(3)

#Normalize the random numbers and multiple by 1000 so that they all add correctly.
p = np.round(p/p.sum()*1000)

print('Starting population: %d alive, %d sick, %d dead '%(p[0],p[1],p[2]))

Starting population: 389 alive, 565 sick, 46 dead 


Now, let's increment the population:

In [11]:
p2 = A@p
print('Starting population: %d alive, %d sick, %d dead '%(p2[0],p2[1],p2[2]))

Starting population: 229 alive, 346 sick, 423 dead 


In [12]:
p2 = np.linalg.matrix_power(A,20)@p
print('Starting population: %d alive, %d sick, %d dead '%(p2[0],p2[1],p2[2]))

Starting population: 0 alive, 0 sick, 999 dead 


Let's do this after n iterations:


In [13]:
p2 = np.linalg.matrix_power(A,20)@p
print('Starting population: %d alive, %d sick, %d dead '%(p2[0],p2[1],p2[2]))

Starting population: 0 alive, 0 sick, 999 dead 


Notice that everyone dies. This happens for any starting configuration. 

## In-class problem: zombies

We discover that there's a 20% chance of a dead person coming back from the dead (a zombie). Calculate the steady state distribution of live, sick, and dead people. 

In [14]:
A = np.array([[0.3,0.2,0.0],
              [0.6,0.2,0.2],
              [0.1,0.6,0.8]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print(eigenvalues)
print(eigenvectors)

[-0.17015621  0.47015621  1.        ]
[[ 0.34604809 -0.44068607  0.08630637]
 [-0.81348329 -0.37492736  0.3020723 ]
 [ 0.4674352   0.81561343  0.94937007]]


In [15]:
p2 = np.linalg.matrix_power(A,20)@p
print('Starting population: %d alive, %d sick, %d dead '%(p2[0],p2[1],p2[2]))

Starting population: 64 alive, 225 sick, 709 dead 
